spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student1?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: 4612
    
server:
  port: 8088   
  
  
  
